stages:
  split:
    cmd: python src/data/split.py
    deps:
      - data/raw_data
      - src/data/split.py
    outs:
      - data/processed_data/X_train.csv
      - data/processed_data/X_test.csv
      - data/processed_data/y_train.csv
      - data/processed_data/y_test.csv

  scale:
    cmd: python src/data/scaled.py
    deps:
      - data/processed_data/X_train.csv
      - data/processed_data/X_test.csv
      - data/processed_data/y_train.csv
      - data/processed_data/y_test.csv
      - src/data/scaled.py
    outs:
      - data/processed_data/X_train_scaled.csv
      - data/processed_data/X_test_scaled.csv

  gridsearch:
    cmd: python src/models/lastgrid.py
    deps:
      - data/processed_data/X_train_scaled.csv
      - data/processed_data/y_train.csv
      - src/models/lastgrid.py
    outs:
      - models/best_params.pkl

  training:
    cmd: python src/models/training2.py
    deps: 
      - src/models/training2.py
      - models/best_params.pkl
      - data/processed_data/X_train_scaled.csv
      - data/processed_data/y_train.csv
    outs:
      - models/best_model.pkl

  evaluation:
    cmd: python src/models/predict.py
    deps:
      - data/processed_data/X_test_scaled.csv
      - data/processed_data/y_test.csv
      - src/models/predict.py
    metrics:
      - metrics/metrics.json
